version: "3.3"

services:
    postgres:
      image: postgres
      container_name: postgresql
      ports: 
        - 5432:5432
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=projeto
      volumes:
        - postgresql_data:/var/lib/postgresql/data
      networks:
        - postgres_network

    postgres_admin:
      image: dpage/pgadmin4
      container_name: postgres_admin
      ports:
        - 80:80
      environment:
        - PGADMIN_DEFAULT_EMAIL=user@dominio.com.br
        - PGADMIN_DEFAULT_PASSWORD=123456
      networks:
        - postgres_network
        
volumes:
    postgresql_data:
      driver: local

networks: 
    postgres_network:
      driver: bridge