version: "3.3"

services:
    sonar:
      image: sonarqube
      container_name: sonar
      ports: 
        - 9000:9000
      environment:
        - SONAR_JDBC_URL=jdbc:postgresql://postgres_sonar:5432/sonar
        - SONAR_JDBC_USERNAME=postgres
        - SONAR_JDBC_PASSWORD=postgres
      volumes:
        - sonar_conf:/opt/sonarqube/conf
        - sonar_logs:/opt/sonarqube/logs
        - sonar_data:/opt/sonarqube/data
        - sonar_extensions:/opt/sonarqube/extensions
      networks:
        - sonar_network
      depends_on:
        - postgres_sonar
  
    postgres_sonar:
      image: postgres
      container_name: postgres_sonar
      ports: 
        - 5432:5432
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=sonar
      volumes:
        - postgresql_sonar_data:/var/lib/postgresql/data
      networks:
        - sonar_network
    
volumes:
    sonar_conf:
      driver: local
    sonar_logs:
      driver: local
    sonar_data:
      driver: local
    sonar_extensions:
      driver: local
    postgresql_sonar_data:
      driver: local
  
networks: 
    sonar_network:
      driver: bridge